# Generated by Django 4.2.1 on 2023-05-27 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_updated',
            field=models.BooleanField(default=False, help_text='編集済みならTrue'),
        ),
        migrations.AddField(
            model_name='post',
            name='is_updated',
            field=models.BooleanField(default=False, help_text='編集済みならTrue'),
        ),
    ]
